name: dctchaotic
channels:
  - defaults
dependencies:
  - ca-certificates=2021.5.25=haa95532_1
  - certifi=2021.5.30=py39haa95532_0
  - openssl=1.1.1k=h2bbff1b_0
  - pip=21.1.2=py39haa95532_0
  - python=3.9.5=h6244533_3
  - setuptools=52.0.0=py39haa95532_0
  - sqlite=3.36.0=h2bbff1b_0
  - tzdata=2021a=h52ac0ba_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.36.2=pyhd3eb1b0_0
  - wincertstore=0.2=py39h2bbff1b_0
  - pip:
    - altgraph==0.17
    - auto-py-to-exe==2.9.0
    - bottle==0.12.19
    - bottle-websocket==0.2.9
    - cffi==1.14.5
    - eel==0.12.4
    - future==0.18.2
    - gevent==21.1.2
    - gevent-websocket==0.10.1
    - greenlet==1.1.0
    - imageio==2.9.0
    - numpy==1.21.0
    - opencv-python==4.5.2.54
    - pefile==2021.5.24
    - pillow==8.2.0
    - pycparser==2.20
    - pyinstaller==4.3
    - pyinstaller-hooks-contrib==2021.2
    - pyqt5==5.15.4
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.9.0
    - pywin32-ctypes==0.2.0
    - scipy==1.7.0
    - whichcraft==0.6.1
    - zope-event==4.5.0
    - zope-interface==5.4.0
